export enum AppAction {
    SET_TEST_TYPE = "APP-REDUCER/SET-TEST-TYPE",
}

export enum QuestionsAction {
    CHANGE_QUESTION_STATUS = "CHANGE-QUESTION-STATUS/QUESTION-REDUCER",
    FETCH_QUESTIONS = "FETCH-QUESTIONS/QUESTION-REDUCER",
    SAVE_CHOSEN_ANSWER = "SAVE-CHOSEN-ANSWER",

}